<?php


namespace Luilliarcec\LaravelEcuadorIdentification\Tests;

use Luilliarcec\LaravelEcuadorIdentification\EcuadorIdentificationServiceProvider;
use Orchestra\Testbench\TestCase as Orchestra;

class TestCase extends Orchestra
{
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    /**
     * Get package providers.
     *
     * @param \Illuminate\Foundation\Application $app
     *
     * @return array
     */
    protected function getPackageProviders($app)
    {
        return [EcuadorIdentificationServiceProvider::class];
    }

    /**
     * Define environment setup.
     *
     * @param \Illuminate\Foundation\Application $app
     *
     * @return void
     */
    protected function getEnvironmentSetUp($app)
    {
        /** Config */
        $app['config']->set('laravel-ecuador-identification', [

            'provinces' => 24,

            'type-identifications' => [
                'ruc' => [
                    'length' => 13,
                    'billing-code' => '04'
                ],

                'personal-identification' => [
                    'length' => 10,
                    'billing-code' => '05',
                ],

                'final-customer' => [
                    'length' => 13,
                    'billing-code' => '07'
                ]
            ],

            'private-ruc' => [
                'third-digit' => 9,
                'last-digits' => '001',
                'coefficients' => [4, 3, 2, 7, 6, 5, 4, 3, 2],
                'check-digit-position' => 10,
            ],

            'public-ruc' => [
                'third-digit' => 6,
                'last-digits' => '0001',
                'coefficients' => [3, 2, 7, 6, 5, 4, 3, 2],
                'check-digit-position' => 9,
            ],

            'natural-ruc' => [
                'last-digits' => '001',
            ],

            'personal-identification' => [
                'third-digit' => [
                    'min' => 0,
                    'max' => 5
                ],
                'coefficients' => [2, 1, 2, 1, 2, 1, 2, 1, 2],
                'check-digit-position' => 10,
            ],

            'final-customer' => [
                'unique-value' => '9999999999999',
            ],
        ]);
    }
}
